/* 
 * File:   main.h
 * Author: francesco
 *
 * Created on May 21, 2021, 5:34 PM
 */

#ifndef MAIN_H
#define	MAIN_H

#ifdef	__cplusplus
extern "C" {
#endif

    
    
    
#include "mcc_generated_files/mcc.h"
#include "motor_handler.h"
#include "stdio.h"
#include "button.h"
#include "servo.h"
#include "RN4871.h"
#include "button.h"



#define IR_SENSOR_THRESHOLD 1200
    
#define FIRST_EE_ADDR 0x7000



// FUNCTION PROTOTYPES

inline void setAddress (uint8_t addr);
// generated by RC4
void encoder1A_InterruptHandler (void);
// generated by RC5
void encoder1B_InterruptHandler (void);
// generated by RC6
void encoder2A_InterruptHandler (void);
// generated by RC7
void encoder2B_InterruptHandler (void);

void TMR1_ISRHandler(void);



void playTone (int duration_ms);
    



#ifdef	__cplusplus
}
#endif

#endif	/* MAIN_H */

